#Creating a Vector

In [ ]:
# Load library
import numpy as np

In [ ]:
# Create a vector as a row
vector_row = np.array([1,2,3])

In [ ]:
vector_row

array([1, 2, 3])

In [ ]:
# Create a vector as a column
vector_column = np.array ([[1],[2],[3]])

In [ ]:
vector_column

array([[1],
       [2],
       [3]])

#Creating a Matrix

In [ ]:
# Create matrix
matrix = np.array([[1,2],[1,2],[1,2]])

In [ ]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
matrix_objet = np.mat([[1,2],[1,2],[1,2]])

In [ ]:
matrix_objet

matrix([[1, 2],
        [1, 2],
        [1, 2]])

However, the matrix data structure is not recommended for two reasons. First, arrays are the de facto
standard data structure of NumPy. Second, the vast majority of NumPy operations return arrays, not
matrix objects.

# Creating a Sparse Matrix

Problem
Given data with very few nonzero values, you want to efficiently represent it

In [ ]:
import numpy as np
from scipy import sparse

In [ ]:
# Create matrix
matrix = np.array([[0,0],[0,1],[3,0]])

In [ ]:
# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [ ]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

A frequent situation in machine learning is having a huge amount of data; however, most of the
elements in the data are zeros. For example, imagine a matrix where the columns are every movie on
Netflix, the rows are every Netflix user, and the values are how many times a user has watched that
particular movie. This matrix would have tens of thousands of columns and millions of rows! However,
since most users do not watch most movies, the vast majority of elements would be zero.
A sparse matrix is a matrix in which most elements are 0. Sparse matrices only store nonzero elements
and assume all other values will be zero, leading to significant computational savings. In our solution,
we created a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view
the sparse matrix we can see that only the nonzero values are stored:

In [ ]:
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices,
(1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively.
For example, the element 1 is in the second row and second column. We can see the advantage of sparse
matrices if we create a much larger matrix with many more zero elements and then compare this larger
matrix with our original sparse matrix:

In [ ]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#Create compressed sparse row (CSR) mmatrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)



in compressed sparse row (CSR) matrices,
(1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively

In [ ]:
#View original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [ ]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse
representation is exactly the same as our original sparse matrix. That is, the addition of zero elements
did not change the size of the sparse matrix.
As mentioned, there are many different types of sparse matrices, such as compressed sparse column, list
of lists, and dictionary of keys. While an explanation of the different types and their implications is
outside the scope of this book, it is worth noting that while there is no “best” sparse matrix type, there
are meaningful differences between them and we should be conscious about why we are choosing one
type over another.

# Pre-allocating Numpy Arrays :
You need to pre-allocate arrays of a given size with some value.

In [5]:
# Load Library
import numpy as np

#Generate a vector of shape (1,5) containing all zeros
vector = np.zeros(shape=5)

In [6]:
 # View the vector
 print(vector)

[0. 0. 0. 0. 0.]


In [7]:
# Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3,3), fill_value=1)

In [8]:
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# Selecting Elements

You need to select one or more elements in a vector or matrix.

In [9]:
# Load Library
import numpy as np

In [10]:
# Create a row vector
vector = np.array([1,2,3,4,5,6])

In [11]:
# Create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])


In [12]:
# Select third element of vector
vector[2]

3

In [13]:
# Select second row
matrix[1,1]

5

Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element
is 0, not 1. With that caveat, NumPy offers a wide variety of methods for selecting (i.e., indexing and
slicing) elements or groups of elements in arrays:

In [14]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [15]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [16]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [17]:
# Select the last element
vector[-1]

6

In [19]:
# Reverse the vector
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [22]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

# Describing a Matrix
You want to describe the shape, size, and dimensions of the matrix