#Creating a Vector

In [1]:
# Load library
import numpy as np

In [5]:
# Create a vector as a row
vector_row = np.array([1,2,3])

In [7]:
vector_row

array([1, 2, 3])

In [3]:
# Create a vector as a column
vector_column = np.array ([[1],[2],[3]])

In [4]:
vector_column

array([[1],
       [2],
       [3]])

#Creating a Matrix

In [8]:
# Create matrix
matrix = np.array([[1,2],[1,2],[1,2]])

In [9]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [10]:
matrix_objet = np.mat([[1,2],[1,2],[1,2]])

In [11]:
matrix_objet

matrix([[1, 2],
        [1, 2],
        [1, 2]])

However, the matrix data structure is not recommended for two reasons. First, arrays are the de facto
standard data structure of NumPy. Second, the vast majority of NumPy operations return arrays, not
matrix objects.

# Creating a Sparse Matrix

Problem
Given data with very few nonzero values, you want to efficiently represent it

In [14]:
import numpy as np
from scipy import sparse

In [15]:
# Create matrix
matrix = np.array([[0,0],[0,1],[3,0]])

In [16]:
# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [17]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

A frequent situation in machine learning is having a huge amount of data; however, most of the
elements in the data are zeros. For example, imagine a matrix where the columns are every movie on
Netflix, the rows are every Netflix user, and the values are how many times a user has watched that
particular movie. This matrix would have tens of thousands of columns and millions of rows! However,
since most users do not watch most movies, the vast majority of elements would be zero.
A sparse matrix is a matrix in which most elements are 0. Sparse matrices only store nonzero elements
and assume all other values will be zero, leading to significant computational savings. In our solution,
we created a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view
the sparse matrix we can see that only the nonzero values are stored:

In [18]:
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices,
(1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively.
For example, the element 1 is in the second row and second column. We can see the advantage of sparse
matrices if we create a much larger matrix with many more zero elements and then compare this larger
matrix with our original sparse matrix:

In [21]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#Create compressed sparse row (CSR) mmatrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)



in compressed sparse row (CSR) matrices,
(1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively

In [22]:
#View original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [23]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse
representation is exactly the same as our original sparse matrix. That is, the addition of zero elements
did not change the size of the sparse matrix.
As mentioned, there are many different types of sparse matrices, such as compressed sparse column, list
of lists, and dictionary of keys. While an explanation of the different types and their implications is
outside the scope of this book, it is worth noting that while there is no “best” sparse matrix type, there
are meaningful differences between them and we should be conscious about why we are choosing one
type over another.