<a href="https://colab.research.google.com/github/AYMAN-CHAREF/machine-learning-et-deep-learning/blob/main/Matrice%20et%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2],[3,4],[5,6]])

In [4]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
A.shape

(3, 2)

In [6]:
B=A.T

In [7]:
B

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
B.shape

(2, 3)

In [9]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
B = np.ones((3,2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
A + B

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [12]:
  A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
B.shape

(3, 2)

In [15]:
A.shape

(3, 2)

In [16]:
A.dot(B)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [17]:
A.dot(B.T)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [18]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
B.T

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
B.T.shape

(2, 3)

In [21]:
A.shape

(3, 2)